# Wallarm API Firewall v0.6.7

FROM wallarm/api-firewall:v0.6.7@sha256:b16bd038f9bd95acb5333d2093b033b05e9d65175879b1bc051f02d8d1ca6dc7
# Supported Bashbrew Architectures: amd64

# For documentation visit https://docs.wallarm.com/api-firewall/overview/
